[identifier]
type = "regex"
condition = "< 1.21.11"
regex = "import net.minecraft.resources.Identifier(?!;)"
to = "import net.minecraft.resources.ResourceLocation as Identifier"
reverseRegex = "import net.minecraft.resources.ResourceLocation as Identifier"
reverse = "import net.minecraft.resources.Identifier"

[named_identifier]
type = "string"
condition = "< 1.21.11"
from = "Identifier"
to = "ResourceLocation"
named = true

[identifier_pattern]
type = "regex"
condition = "< 1.21.11"
regex = "import net.minecraft.util.IdentifierPattern(?!;)"
to = "import net.minecraft.util.ResourceLocationPattern as IdentifierPattern"
reverseRegex = "import net.minecraft.util.ResourceLocationPattern as IdentifierPattern"
reverse = "import net.minecraft.util.IdentifierPattern"

[identifier_argument]
type = "regex"
condition = "< 1.21.11"
regex = "import net.minecraft.commands.arguments.IdentifierArgument(?!;)"
to = "import net.minecraft.commands.arguments.ResourceLocationArgument as IdentifierArgument"
reverseRegex = "import net.minecraft.commands.arguments.ResourceLocationArgument as IdentifierArgument"
reverse = "import net.minecraft.commands.arguments.IdentifierArgument"

[criterion]
type = "string"
condition = "< 1.21.11"
from = "import net.minecraft.advancements.criterion"
to = "import net.minecraft.advancements.critereon"

[render_type]
type = "string"
condition = "< 1.21.11"
from = "import net.minecraft.client.renderer.rendertype.RenderType"
to = "import net.minecraft.client.renderer.RenderType"

[util]
type = "string"
condition = "< 1.21.11"
from = "net.minecraft.util.Util"
to = "net.minecraft.Util"

[player_model]
type = "string"
condition = "< 1.21.11"
from = "net.minecraft.client.model.player.PlayerModel"
to = "net.minecraft.client.model.PlayerModel"

[replacements]
type = "regex"
condition = "< 1.21.11"
regex = "import net.minecraft.client.renderer.RenderTypes(?!;)"
to = "import net.minecraft.client.renderer.RenderType as RenderTypes"
reverseRegex = "import net.minecraft.client.renderer.RenderType as RenderTypes"
reverse = "import net.minecraft.client.renderer.RenderTypes"

[item_holder]
type = "regex"
condition = "<=1.21.8"
regex = "import net.minecraft.world.entity.ItemOwner(?!;)"
to = "import net.minecraft.world.entity.LivingEntity as ItemOwner"
reverseRegex = "import net.minecraft.world.entity.LivingEntity as ItemOwner"
reverse = "import net.minecraft.world.entity.ItemOwner"

[avatar_entity]
type = "string"
condition = "<=1.21.8"
from = "import net.minecraft.client.entity.ClientAvatarEntity"
to = "import net.minecraft.client.player.AbstractClientPlayer as ClientAvatarEntity"
